import type { Day } from '@/types'

function formatDate(startDate: string | undefined, index: number): string | null {
  if (!startDate) return null
  const d = new Date(startDate + 'T00:00:00')
  if (Number.isNaN(d.getTime())) return null
  d.setDate(d.getDate() + index)
  return d.toLocaleDateString(undefined, { weekday: 'short', month: 'short', day: 'numeric' })
}

export function renderPrintableHTML(days: Day[], startDate?: string): string {
  const styles = `
    body { font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Ubuntu, Cantarell, Noto Sans, Arial, 'Apple Color Emoji','Segoe UI Emoji'; margin:0; color:#0F172A; }
    .wrap { max-width: 900px; margin: 24px auto; padding: 0 24px; }
    h1 { font-size: 28px; margin: 0 0 6px; }
    .sub { color:#64748B; margin-bottom: 20px; }
    .day { border:1px solid rgba(2,6,23,0.08); border-radius:16px; padding:16px; margin:12px 0; box-shadow:0 10px 30px rgba(2,6,23,0.06); }
    .day h2 { margin:0 0 10px; font-size:18px; display:flex; align-items:center; gap:8px; }
    .badge { display:inline-block; padding:4px 10px; border-radius:9999px; border:1px solid rgba(2,6,23,0.1); color:#0F172A; font-size:12px; }
    ul { margin: 0; padding-left: 18px; }
    li { margin: 6px 0; }
    .footer { margin-top: 28px; font-size: 12px; color:#94A3B8; }
    .accent { background: linear-gradient(135deg, #16A34A 0%, #F97316 100%); -webkit-background-clip:text; background-clip:text; color:transparent; }
    @media print { .actions { display:none; } .wrap { box-shadow:none; } }
  `

  const body = `
    <div class="wrap">
      <div class="actions">
        <button onclick="window.print()" style="padding:8px 12px;border-radius:10px;border:1px solid rgba(2,6,23,0.1);background:#F8FAFC;cursor:pointer">Print / Save as PDF</button>
      </div>
      <h1 class="accent">Trip Itinerary</h1>
      <div class="sub">${startDate ? `Starting ${new Date(startDate+'T00:00:00').toLocaleDateString()}` : ''}</div>
      ${days.map((d, i) => `
        <section class="day">
          <h2><span class="badge">Day ${i+1}${formatDate(startDate, i)?` · ${formatDate(startDate, i)}`:''}</span> ${d.title}</h2>
          <ul>
            ${d.activities.map(a => `<li>${a.text}${a.start||a.end?` — <em>${a.start||'—'}–${a.end||'—'}</em>`:''}</li>`).join('')}
          </ul>
        </section>
      `).join('')}
      <div class="footer">Generated by AI Itinerary</div>
    </div>
  `

  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">`+
         `<title>Itinerary</title><style>${styles}</style></head><body>${body}</body></html>`
}

